<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Reports\Models\EnterpriseReportTemplate;
use Modules\Reports\Models\ReportSchedule;

/**
 * Seeds the shipped "system" enterprise report templates (config_version = 2)
 * plus example schedules, so every tenant starts with useful, engine-ready
 * reports that can be customised or copied by end users.
 */
class ReportScheduleSeeder extends Seeder
{
    public function run(int $schoolId = 6, int $createdBy = 7): void
    {
        $templates = [
            // ---- Students / Academics ----
            [
                'name' => 'Student Register by Class Stream',
                'report_category' => 'students',
                'module' => 'students',
                'report_type' => 'student_register',
                'datasets' => ['students.register'],
                'joins' => [],
                'selected_fields' => [
                    'students.register.admission_number',
                    'students.register.full_name',
                    'students.register.gender',
                    'students.register.class_name',
                    'students.register.boarding_status',
                    'students.register.status',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'students.register', 'field' => 'class_name', 'direction' => 'asc']],
                'visualizations' => [
                    ['type' => 'bar', 'title' => 'Enrollment by Class', 'label' => 'students.register.class_name', 'series' => [['field' => 'students.register.student_id_number', 'label' => 'Students']]],
                ],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Student Headcount by Status',
                'report_category' => 'students',
                'module' => 'students',
                'report_type' => 'student_headcount',
                'datasets' => ['students.register'],
                'joins' => [],
                'selected_fields' => ['students.register.status'],
                'filters' => [],
                'grouping' => ['students.register.status'],
                'calculations' => [['type' => 'count', 'field' => 'students.register.id', 'alias' => 'student_count']],
                'sorting' => [['dataset' => 'students.register', 'field' => 'status', 'direction' => 'asc']],
                'visualizations' => [
                    ['type' => 'pie', 'title' => 'Students by Status', 'label' => 'students.register.status', 'series' => [['field' => 'student_count', 'label' => 'Students']]],
                ],
                'orientation' => 'portrait',
            ],
            [
                'name' => 'Student Medical Profiles',
                'report_category' => 'students',
                'module' => 'clinic',
                'report_type' => 'medical_profiles',
                'datasets' => ['students.register', 'clinic.medical_record'],
                'joins' => [['from' => 'students.register', 'to' => 'clinic.medical_record', 'type' => 'left']],
                'selected_fields' => [
                    'students.register.full_name',
                    'students.register.class_name',
                    'students.register.blood_group',
                    'clinic.medical_record.allergies',
                    'clinic.medical_record.chronic_conditions',
                    'clinic.medical_record.regular_medications',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'students.register', 'field' => 'class_name', 'direction' => 'asc']],
                'visualizations' => [],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Academic Performance Summary',
                'report_category' => 'academics',
                'module' => 'academics',
                'report_type' => 'performance_summary',
                'datasets' => ['academics.performance', 'students.register'],
                'joins' => [['from' => 'academics.performance', 'to' => 'students.register', 'type' => 'left']],
                'selected_fields' => [
                    'students.register.full_name',
                    'students.register.class_name',
                    'academics.performance.subjects_taken',
                    'academics.performance.average_mark',
                    'academics.performance.score_percent',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'academics.performance', 'field' => 'score_percent', 'direction' => 'desc']],
                'visualizations' => [
                    ['type' => 'bar', 'title' => 'Performance by Class', 'label' => 'students.register.class_name', 'series' => [['field' => 'academics.performance.score_percent', 'label' => 'Average %']]],
                ],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Student Marks Ledger',
                'report_category' => 'academics',
                'module' => 'academics',
                'report_type' => 'marks_ledger',
                'datasets' => ['academics.mark_record'],
                'joins' => [],
                'selected_fields' => [
                    'academics.mark_record.student_name',
                    'academics.mark_record.course_name',
                    'academics.mark_record.section_name',
                    'academics.mark_record.subject_name',
                    'academics.mark_record.paper_name',
                    'academics.mark_record.total_score',
                    'academics.mark_record.average_score',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'academics.mark_record', 'field' => 'student_name', 'direction' => 'asc']],
                'visualizations' => [],
                'orientation' => 'landscape',
            ],

            // ---- Attendance ----
            [
                'name' => 'Attendance by Class Stream',
                'report_category' => 'attendance',
                'module' => 'attendance',
                'report_type' => 'attendance_by_class',
                'datasets' => ['attendance.class_summary'],
                'joins' => [],
                'selected_fields' => [
                    'attendance.class_summary.class_name',
                    'attendance.class_summary.total_students',
                    'attendance.class_summary.present_days',
                    'attendance.class_summary.absent_days',
                    'attendance.class_summary.late_days',
                    'attendance.class_summary.attendance_rate',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'attendance.class_summary', 'field' => 'attendance_rate', 'direction' => 'asc']],
                'visualizations' => [
                    ['type' => 'bar', 'title' => 'Attendance Rate by Class', 'label' => 'attendance.class_summary.class_name', 'series' => [['field' => 'attendance.class_summary.attendance_rate', 'label' => 'Attendance %']]],
                ],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Attendance Monthly Trend',
                'report_category' => 'attendance',
                'module' => 'attendance',
                'report_type' => 'attendance_trend',
                'datasets' => ['attendance.monthly_trend'],
                'joins' => [],
                'selected_fields' => [
                    'attendance.monthly_trend.month',
                    'attendance.monthly_trend.total_records',
                    'attendance.monthly_trend.present_days',
                    'attendance.monthly_trend.absent_days',
                    'attendance.monthly_trend.attendance_rate',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'attendance.monthly_trend', 'field' => 'month', 'direction' => 'asc']],
                'visualizations' => [
                    ['type' => 'line', 'title' => 'Attendance Rate over Time', 'label' => 'attendance.monthly_trend.month', 'series' => [['field' => 'attendance.monthly_trend.attendance_rate', 'label' => 'Attendance %']]],
                ],
                'orientation' => 'portrait',
            ],

            // ---- Finance ----
            [
                'name' => 'Fee Defaulters (Cross-Module)',
                'report_category' => 'finance',
                'module' => 'finance',
                'report_type' => 'fee_balances',
                'datasets' => ['finance.balance', 'students.register'],
                'joins' => [['from' => 'finance.balance', 'to' => 'students.register', 'type' => 'left']],
                'selected_fields' => [
                    'students.register.full_name',
                    'students.register.class_name',
                    'finance.balance.invoice_count',
                    'finance.balance.total_invoiced',
                    'finance.balance.total_paid',
                    'finance.balance.outstanding_balance',
                ],
                'filters' => [['dataset' => 'finance.balance', 'key' => 'outstanding_balance', 'op' => 'gt', 'value' => 0]],
                'grouping' => [],
                'calculations' => [
                    ['type' => 'sum', 'field' => 'finance.balance.outstanding_balance', 'alias' => 'total_outstanding'],
                ],
                'sorting' => [['dataset' => 'finance.balance', 'field' => 'outstanding_balance', 'direction' => 'desc']],
                'visualizations' => [
                    ['type' => 'doughnut', 'title' => 'Outstanding by Class', 'label' => 'students.register.class_name', 'series' => [['field' => 'finance.balance.outstanding_balance', 'label' => 'Outstanding']]],
                ],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Overdue Invoices',
                'report_category' => 'finance',
                'module' => 'finance',
                'report_type' => 'overdue_invoices',
                'datasets' => ['finance.invoice'],
                'joins' => [],
                'selected_fields' => [
                    'finance.invoice.invoice_number',
                    'finance.invoice.student_name',
                    'finance.invoice.class_name',
                    'finance.invoice.total_amount',
                    'finance.invoice.paid_amount',
                    'finance.invoice.balance_amount',
                    'finance.invoice.due_date',
                    'finance.invoice.is_overdue',
                ],
                'filters' => [['dataset' => 'finance.invoice', 'key' => 'is_overdue', 'op' => 'eq', 'value' => 1]],
                'grouping' => [],
                'calculations' => [['type' => 'sum', 'field' => 'finance.invoice.balance_amount', 'alias' => 'total_overdue']],
                'sorting' => [['dataset' => 'finance.invoice', 'field' => 'due_date', 'direction' => 'asc']],
                'visualizations' => [],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Monthly Revenue Collections',
                'report_category' => 'finance',
                'module' => 'finance',
                'report_type' => 'revenue_summary',
                'datasets' => ['finance.revenue_summary'],
                'joins' => [],
                'selected_fields' => [
                    'finance.revenue_summary.month',
                    'finance.revenue_summary.payment_count',
                    'finance.revenue_summary.net_collected',
                    'finance.revenue_summary.cash_collected',
                    'finance.revenue_summary.other_collected',
                    'finance.revenue_summary.reversed_amount',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'finance.revenue_summary', 'field' => 'month', 'direction' => 'desc']],
                'visualizations' => [
                    ['type' => 'line', 'title' => 'Monthly Collections', 'label' => 'finance.revenue_summary.month', 'series' => [['field' => 'finance.revenue_summary.net_collected', 'label' => 'Net Collected']]],
                ],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Payment Receipts Ledger',
                'report_category' => 'finance',
                'module' => 'finance',
                'report_type' => 'payment_ledger',
                'datasets' => ['finance.payment'],
                'joins' => [],
                'selected_fields' => [
                    'finance.payment.receipt_number',
                    'finance.payment.student_name',
                    'finance.payment.invoice_number',
                    'finance.payment.amount',
                    'finance.payment.payment_method',
                    'finance.payment.payment_date',
                    'finance.payment.is_reversed',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [['type' => 'sum', 'field' => 'finance.payment.amount', 'alias' => 'total_collected']],
                'sorting' => [['dataset' => 'finance.payment', 'field' => 'payment_date', 'direction' => 'desc']],
                'visualizations' => [],
                'orientation' => 'landscape',
            ],

            // ---- Admissions ----
            [
                'name' => 'Admissions Pipeline',
                'report_category' => 'admissions',
                'module' => 'admissions',
                'report_type' => 'admissions_funnel',
                'datasets' => ['admissions.funnel'],
                'joins' => [],
                'selected_fields' => [
                    'admissions.funnel.status',
                    'admissions.funnel.application_count',
                    'admissions.funnel.male_count',
                    'admissions.funnel.female_count',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'admissions.funnel', 'field' => 'application_count', 'direction' => 'desc']],
                'visualizations' => [
                    ['type' => 'bar', 'title' => 'Applications by Status', 'label' => 'admissions.funnel.status', 'series' => [['field' => 'admissions.funnel.application_count', 'label' => 'Applications']]],
                ],
                'orientation' => 'portrait',
            ],
            [
                'name' => 'Admission Applications (detail)',
                'report_category' => 'admissions',
                'module' => 'admissions',
                'report_type' => 'applications_list',
                'datasets' => ['admissions.application'],
                'joins' => [],
                'selected_fields' => [
                    'admissions.application.application_number',
                    'admissions.application.full_name',
                    'admissions.application.course_name',
                    'admissions.application.gender',
                    'admissions.application.parent_name',
                    'admissions.application.parent_phone',
                    'admissions.application.status',
                    'admissions.application.created_at',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'admissions.application', 'field' => 'created_at', 'direction' => 'desc']],
                'visualizations' => [],
                'orientation' => 'landscape',
            ],

            // ---- Timetable ----
            [
                'name' => 'Timetable by Teacher',
                'report_category' => 'timetable',
                'module' => 'timetable',
                'report_type' => 'timetable_teacher',
                'datasets' => ['timetable.lesson'],
                'joins' => [],
                'selected_fields' => [
                    'timetable.lesson.teacher_name',
                    'timetable.lesson.day_name',
                    'timetable.lesson.slot_start',
                    'timetable.lesson.slot_end',
                    'timetable.lesson.subject_name',
                    'timetable.lesson.course_name',
                    'timetable.lesson.section_name',
                    'timetable.lesson.classroom_name',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'timetable.lesson', 'field' => 'teacher_name', 'direction' => 'asc']],
                'visualizations' => [],
                'orientation' => 'landscape',
            ],

            // ---- Library / Hostel / Clinic ----
            [
                'name' => 'Book Circulation',
                'report_category' => 'library',
                'module' => 'library',
                'report_type' => 'book_circulation',
                'datasets' => ['library.issue'],
                'joins' => [],
                'selected_fields' => [
                    'library.issue.book_title',
                    'library.issue.student_name',
                    'library.issue.class_name',
                    'library.issue.issued_at',
                    'library.issue.due_at',
                    'library.issue.returned_at',
                    'library.issue.status',
                    'library.issue.fine_amount',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'library.issue', 'field' => 'issued_at', 'direction' => 'desc']],
                'visualizations' => [
                    ['type' => 'bar', 'title' => 'Circulation by Status', 'label' => 'library.issue.status', 'series' => [['field' => 'library.issue.renewals_count', 'label' => 'Issues']]],
                ],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Overdue Books',
                'report_category' => 'library',
                'module' => 'library',
                'report_type' => 'overdue_books',
                'datasets' => ['library.overdue_summary'],
                'joins' => [],
                'selected_fields' => [
                    'library.overdue_summary.student_name',
                    'library.overdue_summary.admission_number',
                    'library.overdue_summary.book_title',
                    'library.overdue_summary.due_at',
                    'library.overdue_summary.days_overdue',
                    'library.overdue_summary.fine_amount',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'library.overdue_summary', 'field' => 'days_overdue', 'direction' => 'desc']],
                'visualizations' => [],
                'orientation' => 'portrait',
            ],
            [
                'name' => 'Hostel Occupancy',
                'report_category' => 'hostel',
                'module' => 'boarding',
                'report_type' => 'hostel_occupancy',
                'datasets' => ['hostel.allocation'],
                'joins' => [],
                'selected_fields' => [
                    'hostel.allocation.student_name',
                    'hostel.allocation.hostel_name',
                    'hostel.allocation.building_name',
                    'hostel.allocation.room_number',
                    'hostel.allocation.bed_number',
                    'hostel.allocation.allocated_at',
                    'hostel.allocation.status',
                ],
                'filters' => [['dataset' => 'hostel.allocation', 'key' => 'status', 'op' => 'eq', 'value' => 'active']],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'hostel.allocation', 'field' => 'hostel_name', 'direction' => 'asc']],
                'visualizations' => [
                    ['type' => 'bar', 'title' => 'Occupancy by Hostel', 'label' => 'hostel.allocation.hostel_name', 'series' => [['field' => 'hostel.allocation.id', 'label' => 'Beds']]],
                ],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Clinic Visits Monthly',
                'report_category' => 'clinic',
                'module' => 'clinic',
                'report_type' => 'clinic_visits',
                'datasets' => ['clinic.visit_summary'],
                'joins' => [],
                'selected_fields' => [
                    'clinic.visit_summary.month',
                    'clinic.visit_summary.visit_count',
                    'clinic.visit_summary.unique_students',
                    'clinic.visit_summary.referral_count',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'clinic.visit_summary', 'field' => 'month', 'direction' => 'desc']],
                'visualizations' => [
                    ['type' => 'line', 'title' => 'Sick-bay visits per month', 'label' => 'clinic.visit_summary.month', 'series' => [['field' => 'clinic.visit_summary.visit_count', 'label' => 'Visits']]],
                ],
                'orientation' => 'portrait',
            ],

            // ---- Inventory / Assets / Procurement ----
            [
                'name' => 'Inventory Stock Status',
                'report_category' => 'inventory',
                'module' => 'inventory',
                'report_type' => 'stock_levels',
                'datasets' => ['inventory.item'],
                'joins' => [],
                'selected_fields' => [
                    'inventory.item.sku',
                    'inventory.item.name',
                    'inventory.item.current_quantity',
                    'inventory.item.reorder_level',
                    'inventory.item.average_unit_cost',
                    'inventory.item.stock_value',
                    'inventory.item.low_stock',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [
                    ['type' => 'sum', 'field' => 'inventory.item.stock_value', 'alias' => 'total_stock_value'],
                ],
                'sorting' => [['dataset' => 'inventory.item', 'field' => 'stock_value', 'direction' => 'desc']],
                'visualizations' => [
                    ['type' => 'bar', 'title' => 'Stock Value by Item', 'label' => 'inventory.item.name', 'series' => [['field' => 'inventory.item.stock_value', 'label' => 'Stock Value']]],
                ],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Low Stock Items',
                'report_category' => 'inventory',
                'module' => 'inventory',
                'report_type' => 'low_stock',
                'datasets' => ['inventory.item'],
                'joins' => [],
                'selected_fields' => [
                    'inventory.item.sku',
                    'inventory.item.name',
                    'inventory.item.category_name',
                    'inventory.item.current_quantity',
                    'inventory.item.reorder_level',
                    'inventory.item.low_stock',
                ],
                'filters' => [['dataset' => 'inventory.item', 'key' => 'low_stock', 'op' => 'eq', 'value' => 1]],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'inventory.item', 'field' => 'current_quantity', 'direction' => 'asc']],
                'visualizations' => [],
                'orientation' => 'portrait',
            ],
            [
                'name' => 'Fixed Assets Register',
                'report_category' => 'inventory',
                'module' => 'inventory',
                'report_type' => 'fixed_assets',
                'datasets' => ['assets.fixed_asset'],
                'joins' => [],
                'selected_fields' => [
                    'assets.fixed_asset.asset_number',
                    'assets.fixed_asset.serial_number',
                    'assets.fixed_asset.item_name',
                    'assets.fixed_asset.acquisition_date',
                    'assets.fixed_asset.purchase_cost',
                    'assets.fixed_asset.current_value',
                    'assets.fixed_asset.status',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [['type' => 'sum', 'field' => 'assets.fixed_asset.current_value', 'alias' => 'total_asset_value']],
                'sorting' => [['dataset' => 'assets.fixed_asset', 'field' => 'current_value', 'direction' => 'desc']],
                'visualizations' => [],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Asset Maintenance Log',
                'report_category' => 'inventory',
                'module' => 'inventory',
                'report_type' => 'asset_maintenance',
                'datasets' => ['assets.maintenance'],
                'joins' => [],
                'selected_fields' => [
                    'assets.maintenance.asset_number',
                    'assets.maintenance.title',
                    'assets.maintenance.type',
                    'assets.maintenance.scheduled_date',
                    'assets.maintenance.completed_date',
                    'assets.maintenance.cost',
                    'assets.maintenance.status',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'assets.maintenance', 'field' => 'scheduled_date', 'direction' => 'desc']],
                'visualizations' => [],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Purchase Orders',
                'report_category' => 'inventory',
                'module' => 'inventory',
                'report_type' => 'purchase_orders',
                'datasets' => ['procurement.order'],
                'joins' => [],
                'selected_fields' => [
                    'procurement.order.order_number',
                    'procurement.order.supplier_name',
                    'procurement.order.order_date',
                    'procurement.order.expected_delivery_date',
                    'procurement.order.total_amount',
                    'procurement.order.status',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [['type' => 'sum', 'field' => 'procurement.order.total_amount', 'alias' => 'total_orders']],
                'sorting' => [['dataset' => 'procurement.order', 'field' => 'order_date', 'direction' => 'desc']],
                'visualizations' => [],
                'orientation' => 'landscape',
            ],

            // ---- HR / Payroll ----
            [
                'name' => 'HR Leave Requests',
                'report_category' => 'hr',
                'module' => 'hr',
                'report_type' => 'leave_requests',
                'datasets' => ['hr.leave_request'],
                'joins' => [],
                'selected_fields' => [
                    'hr.leave_request.employee_name',
                    'hr.leave_request.leave_type',
                    'hr.leave_request.start_date',
                    'hr.leave_request.end_date',
                    'hr.leave_request.status',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'hr.leave_request', 'field' => 'start_date', 'direction' => 'desc']],
                'visualizations' => [],
                'orientation' => 'portrait',
            ],
            [
                'name' => 'Payroll Summary by Department',
                'report_category' => 'hr',
                'module' => 'hr',
                'report_type' => 'payroll_by_department',
                'datasets' => ['payroll.payslip'],
                'joins' => [],
                'selected_fields' => ['payroll.payslip.department'],
                'filters' => [],
                'grouping' => ['payroll.payslip.department'],
                'calculations' => [
                    ['type' => 'count', 'field' => 'payroll.payslip.id', 'alias' => 'payslip_count'],
                    ['type' => 'sum', 'field' => 'payroll.payslip.gross_pay', 'alias' => 'total_gross'],
                    ['type' => 'sum', 'field' => 'payroll.payslip.net_pay', 'alias' => 'total_net'],
                ],
                'sorting' => [['dataset' => 'payroll.payslip', 'field' => 'department', 'direction' => 'asc']],
                'visualizations' => [
                    ['type' => 'bar', 'title' => 'Gross Pay by Department', 'label' => 'payroll.payslip.department', 'series' => [['field' => 'total_gross', 'label' => 'Gross']]],
                ],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Employee Register',
                'report_category' => 'hr',
                'module' => 'hr',
                'report_type' => 'employee_register',
                'datasets' => ['hr.employee'],
                'joins' => [],
                'selected_fields' => [
                    'hr.employee.employee_number',
                    'hr.employee.full_name',
                    'hr.employee.department',
                    'hr.employee.designation',
                    'hr.employee.employment_type',
                    'hr.employee.date_joined',
                    'hr.employee.phone_number',
                    'hr.employee.email',
                    'hr.employee.status',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'hr.employee', 'field' => 'department', 'direction' => 'asc']],
                'visualizations' => [],
                'orientation' => 'landscape',
            ],
            [
                'name' => 'Staff Disciplinary Cases',
                'report_category' => 'hr',
                'module' => 'hr',
                'report_type' => 'disciplinary_cases',
                'datasets' => ['discipline.case'],
                'joins' => [],
                'selected_fields' => [
                    'discipline.case.employee_name',
                    'discipline.case.offense',
                    'discipline.case.incident_date',
                    'discipline.case.severity',
                    'discipline.case.status',
                    'discipline.case.resolution_notes',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'discipline.case', 'field' => 'incident_date', 'direction' => 'desc']],
                'visualizations' => [],
                'orientation' => 'portrait',
            ],

            // ---- Operations / System ----
            [
                'name' => 'Helpdesk Tickets',
                'report_category' => 'communication',
                'module' => 'communication',
                'report_type' => 'helpdesk_tickets',
                'datasets' => ['communication.ticket'],
                'joins' => [],
                'selected_fields' => [
                    'communication.ticket.ticket_number',
                    'communication.ticket.category',
                    'communication.ticket.subject',
                    'communication.ticket.priority',
                    'communication.ticket.status',
                    'communication.ticket.created_at',
                    'communication.ticket.resolved_at',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'communication.ticket', 'field' => 'created_at', 'direction' => 'desc']],
                'visualizations' => [],
                'orientation' => 'portrait',
            ],
            [
                'name' => 'System Audit Trail',
                'report_category' => 'administration',
                'module' => 'administration',
                'report_type' => 'audit_trail',
                'datasets' => ['system.audit_log'],
                'joins' => [],
                'selected_fields' => [
                    'system.audit_log.created_at',
                    'system.audit_log.user_name',
                    'system.audit_log.action',
                    'system.audit_log.module',
                    'system.audit_log.outcome',
                    'system.audit_log.ip_address',
                ],
                'filters' => [],
                'grouping' => [],
                'calculations' => [],
                'sorting' => [['dataset' => 'system.audit_log', 'field' => 'created_at', 'direction' => 'desc']],
                'visualizations' => [],
                'orientation' => 'landscape',
            ],
        ];

        foreach ($templates as $template) {
            EnterpriseReportTemplate::updateOrCreate(
                ['school_id' => $schoolId, 'name' => $template['name']],
                array_merge($template, [
                    'config_version' => 2,
                    'is_system' => true,
                    'layout_settings' => [
                        'primary_color' => '#15803d',
                        'show_logo' => true,
                        'show_signature_block' => true,
                        'header_text' => 'OFFICIAL INSTITUTIONAL RECORD',
                        'footer_text' => 'Confidential - Generated via SchoolCore ERP Reporting System.',
                    ],
                    'created_by_id' => $createdBy,
                ])
            );
        }

        $this->seedSchedules($schoolId);
    }

    protected function seedSchedules(int $schoolId): void
    {
        $templateIdFor = fn (string $name) => EnterpriseReportTemplate::where('school_id', $schoolId)
            ->where('name', $name)->value('id');

        // Example schedule for the defaulter report.
        ReportSchedule::updateOrCreate(
            ['school_id' => $schoolId, 'name' => 'Monthly Defaulters Distribution'],
            [
                'enterprise_report_template_id' => $templateIdFor('Fee Defaulters (Cross-Module)'),
                'frequency' => 'monthly',
                'distribution_method' => 'email',
                'output_format' => 'pdf',
                'generate_on_demand' => true,
                'recipients' => ['bursar@example.com'],
                'filter_overrides' => [],
                'is_active' => true,
                'next_run_at' => now()->addMonth(),
            ]
        );

        ReportSchedule::updateOrCreate(
            ['school_id' => $schoolId, 'name' => 'Weekly Attendance Health'],
            [
                'enterprise_report_template_id' => $templateIdFor('Attendance by Class Stream'),
                'frequency' => 'weekly',
                'distribution_method' => 'email',
                'output_format' => 'pdf',
                'generate_on_demand' => true,
                'recipients' => ['headteacher@example.com'],
                'filter_overrides' => [],
                'is_active' => true,
                'next_run_at' => now()->addWeek(),
            ]
        );

        ReportSchedule::updateOrCreate(
            ['school_id' => $schoolId, 'name' => 'Monthly Revenue Roll-up'],
            [
                'enterprise_report_template_id' => $templateIdFor('Monthly Revenue Collections'),
                'frequency' => 'monthly',
                'distribution_method' => 'email',
                'output_format' => 'xlsx',
                'generate_on_demand' => true,
                'recipients' => ['finance@example.com'],
                'filter_overrides' => [],
                'is_active' => true,
                'next_run_at' => now()->addMonth(),
            ]
        );
    }
}
