<?php

namespace Modules\CMS\Services;

/**
 * ComponentRegistry
 *
 * Central catalog of every reusable content schema ("component") that a school
 * website can render, plus its swappable presentation variants.
 *
 * This is the source of truth the page builder uses to auto-generate the
 * grouped edit form for a section (Content / Layout / Appearance / Animation /
 * Responsive / Advanced), and the renderer uses to dispatch a block to the
 * right partial for its active variant.
 *
 * A "template" is nothing more than a named, ordered list of blocks that each
 * reference a component_key + variant_key — there is no per-template markup.
 *
 * @see CmsTemplateService  (starter defaults, tokens)
 */
class ComponentRegistry
{
    public const GROUP_CONTENT = 'content';

    public const GROUP_LAYOUT = 'layout';

    public const GROUP_APPEARANCE = 'appearance';

    public const GROUP_ANIMATION = 'animation';

    public const GROUP_RESPONSIVE = 'responsive';

    public const GROUP_ADVANCED = 'advanced';

    /** Field types the schema-driven editor form understands. */
    public const TYPES = [
        'text', 'textarea', 'rich_text', 'url', 'image', 'image_list',
        'list', 'select', 'color', 'number', 'range', 'toggle', 'group',
    ];

    /**
     * Placeholder image keys -> asset path (relative to public/). Generated by
     * the `cms:seed-placeholders` command. Templates only ever reference these
     * or the tenant's own uploads — never third-party CDNs.
     */
    public const PLACEHOLDER_IMAGES = [
        'campus-exterior' => 'images/placeholders/campus-exterior.svg',
        'campus-quad' => 'images/placeholders/campus-quad.svg',
        'classroom' => 'images/placeholders/classroom.svg',
        'library' => 'images/placeholders/library.svg',
        'science-lab' => 'images/placeholders/science-lab.svg',
        'sports-field' => 'images/placeholders/sports-field.svg',
        'assembly-hall' => 'images/placeholders/assembly-hall.svg',
        'students-library' => 'images/placeholders/students-library.svg',
        'students-outdoor' => 'images/placeholders/students-outdoor.svg',
        'cafeteria' => 'images/placeholders/cafeteria.svg',
        'arts-studio' => 'images/placeholders/arts-studio.svg',
        'staff-silhouette' => 'images/placeholders/staff-silhouette.svg',
        'logo-placeholder' => 'images/placeholders/logo-placeholder.svg',
        'event-cover' => 'images/placeholders/event-cover.svg',
        'news-cover' => 'images/placeholders/news-cover.svg',
    ];

    /** The ten system site templates (replacing the legacy token-only set). */
    public const SYSTEM_TEMPLATES = [
        'heritage-editorial' => [
            'name' => 'Heritage Editorial',
            'subtitle' => 'Traditional • Trustworthy • Established',
            'description' => 'Serif display type, navy/cream/gold palette, symmetric grids, subtle fade-in-on-scroll only.',
            'fonts' => ['primary' => 'Libre Baskerville', 'secondary' => 'Playfair Display'],
            'palette' => [
                'primary' => '#1f3a5f', 'secondary' => '#2e5a88', 'accent' => '#b08d3f',
                'background' => '#faf7f0', 'text' => '#1a2332', 'card_bg' => '#ffffff',
            ],
            'design' => ['radius' => 'none', 'shadow' => 'sm', 'container' => 'boxed', 'button_style' => 'square'],
        ],
        'cinematic-immersive' => [
            'name' => 'Cinematic Immersive',
            'subtitle' => 'Motion-forward • Signature Showcase',
            'description' => 'Living aurora canvas hero with kinetic reveal headlines, inverting light/dark sections and continuous motion language.',
            'fonts' => ['primary' => 'Inter', 'secondary' => 'Space Grotesk'],
            'palette' => [
                'primary' => '#0b0f19', 'secondary' => '#06b6d4', 'accent' => '#f43f5e',
                'background' => '#0b0f19', 'text' => '#f8fafc', 'card_bg' => '#111827',
            ],
            'design' => ['radius' => 'md', 'shadow' => 'lg', 'container' => 'wide', 'button_style' => 'rounded'],
        ],
        'modern-vibrant' => [
            'name' => 'Modern Vibrant',
            'subtitle' => 'Youthful • Energetic • Bold',
            'description' => 'Bold color-blocked sections, coverflow student-life showcase, continuous marquee ticker.',
            'fonts' => ['primary' => 'Plus Jakarta Sans', 'secondary' => 'Space Grotesk'],
            'palette' => [
                'primary' => '#7c3aed', 'secondary' => '#06b6d4', 'accent' => '#f59e0b',
                'background' => '#ffffff', 'text' => '#1e293b', 'card_bg' => '#f8fafc',
            ],
            'design' => ['radius' => 'lg', 'shadow' => 'md', 'container' => 'wide', 'button_style' => 'pill'],
        ],
        'minimalist-academic' => [
            'name' => 'Minimalist Academic',
            'subtitle' => 'Quiet • Restrained • Prestige',
            'description' => 'Generous whitespace, single accent color, type-driven micro-motion and progressive text highlight.',
            'fonts' => ['primary' => 'Inter', 'secondary' => 'Fraunces'],
            'palette' => [
                'primary' => '#0f172a', 'secondary' => '#334155', 'accent' => '#d97706',
                'background' => '#ffffff', 'text' => '#111827', 'card_bg' => '#f8fafc',
            ],
            'design' => ['radius' => 'sm', 'shadow' => 'sm', 'container' => 'boxed', 'button_style' => 'square'],
        ],
        'community-warm' => [
            'name' => 'Community Warm',
            'subtitle' => 'Family-oriented • Photo-heavy • Earth tones',
            'description' => 'Rounded corners, orbit gallery, optional interactive globe for the global community section.',
            'fonts' => ['primary' => 'Nunito', 'secondary' => 'Merriweather'],
            'palette' => [
                'primary' => '#9a3412', 'secondary' => '#b45309', 'accent' => '#65a30d',
                'background' => '#fef7ed', 'text' => '#3f2415', 'card_bg' => '#ffffff',
            ],
            'design' => ['radius' => 'xl', 'shadow' => 'md', 'container' => 'wide', 'button_style' => 'pill'],
        ],

        // ── Round two (the "design library" set) ───────────────────────
        'coastal-fresh' => [
            'name' => 'Coastal Fresh',
            'subtitle' => 'Airy • Seafoam & Sky • Open',
            'description' => 'Breezy coastal palette with soft sky-to-seafoam gradients, a round photo carousel and rounded friendly cards.',
            'fonts' => ['primary' => 'Quicksand', 'secondary' => 'DM Serif Display'],
            'palette' => [
                'primary' => '#0e7490', 'secondary' => '#06b6d4', 'accent' => '#f59e0b',
                'background' => '#f4fbfe', 'text' => '#164e63', 'card_bg' => '#ffffff',
            ],
            'design' => ['radius' => 'lg', 'shadow' => 'md', 'container' => 'wide', 'button_style' => 'pill'],
        ],
        'playful-garden' => [
            'name' => 'Playful Garden',
            'subtitle' => 'Junior-school • Bright • Bubbly',
            'description' => 'Cheerful coral/teal/yellow palette for primary schools, oversized rounded shapes, gradient blobs and photo-led sections.',
            'fonts' => ['primary' => 'Nunito', 'secondary' => 'Baloo 2'],
            'palette' => [
                'primary' => '#f43f5e', 'secondary' => '#14b8a6', 'accent' => '#fbbf24',
                'background' => '#fffaf3', 'text' => '#43231f', 'card_bg' => '#ffffff',
            ],
            'design' => ['radius' => 'xl', 'shadow' => 'md', 'container' => 'wide', 'button_style' => 'pill'],
        ],
        'emerald-heritage' => [
            'name' => 'Emerald Heritage',
            'subtitle' => 'Forest green • Serif • Prestige',
            'description' => 'Deep forest green and antique gold with elegant serif display type, editorial coverflow and refined card systems.',
            'fonts' => ['primary' => 'Montserrat', 'secondary' => 'Cormorant Garamond'],
            'palette' => [
                'primary' => '#14532d', 'secondary' => '#166534', 'accent' => '#c9a24b',
                'background' => '#f7f5ef', 'text' => '#1f2d24', 'card_bg' => '#ffffff',
            ],
            'design' => ['radius' => 'sm', 'shadow' => 'sm', 'container' => 'boxed', 'button_style' => 'square'],
        ],
        'neon-frontier' => [
            'name' => 'Neon Frontier',
            'subtitle' => 'STEM • Dark • Electric',
            'description' => 'Dark indigo canvas with electric cyan and lime glows, glassmorphism surfaces, mono labels and a coverflow showcase.',
            'fonts' => ['primary' => 'Sora', 'secondary' => 'JetBrains Mono'],
            'palette' => [
                'primary' => '#4f46e5', 'secondary' => '#22d3ee', 'accent' => '#a3e635',
                'background' => '#0b1021', 'text' => '#e5e7eb', 'card_bg' => '#151d38',
            ],
            'design' => ['radius' => 'md', 'shadow' => 'lg', 'container' => 'wide', 'button_style' => 'rounded'],
        ],
        'sunset-international' => [
            'name' => 'Sunset International',
            'subtitle' => 'Global • Terracotta & Teal • Warm',
            'description' => 'International-school warmth with terracotta sunsets over deep teal, accreditation logo cloud and a global orbit gallery.',
            'fonts' => ['primary' => 'Rubik', 'secondary' => 'Playfair Display'],
            'palette' => [
                'primary' => '#0f766e', 'secondary' => '#b45309', 'accent' => '#ea580c',
                'background' => '#fdfaf3', 'text' => '#292524', 'card_bg' => '#ffffff',
            ],
            'design' => ['radius' => 'lg', 'shadow' => 'md', 'container' => 'wide', 'button_style' => 'pill'],
        ],
    ];

    /** @var array<string, array{name: string, category: string, ...}> */
    private static ?array $catalog = null;

    /** @var array<string, array<string, array>> */
    private static ?array $variants = null;

    public static function placeholderImages(): array
    {
        return self::PLACEHOLDER_IMAGES;
    }

    public static function placeholderUrl(string $key, string $fallback = 'campus-exterior'): string
    {
        $path = self::PLACEHOLDER_IMAGES[$key] ?? self::PLACEHOLDER_IMAGES[$fallback] ?? self::PLACEHOLDER_IMAGES['campus-exterior'];

        return asset($path);
    }

    /** True when an image URL points at one of our shipped placeholders. */
    public static function isPlaceholder(?string $url): bool
    {
        if ($url === null || $url === '') {
            return false;
        }
        foreach (self::PLACEHOLDER_IMAGES as $path) {
            if (str_contains($url, $path)) {
                return true;
            }
        }

        return false;
    }

    /** Spec-facing hyphenated key -> data-model block type. */
    public static function typeFromSpecKey(string $specKey): string
    {
        $map = [
            'orbit-gallery' => 'orbit_gallery',
            'coverflow-carousel' => 'coverflow_carousel',
            'marquee-ticker' => 'marquee_ticker',
            'kinetic-reveal-heading' => 'kinetic_reveal_heading',
            'scroll-highlight-text' => 'scroll_highlight_text',
            'stat-globe' => 'stat_globe',
            'depth-text' => 'depth_text',
            'hero-cinematic-scroll' => 'cinematic_scroll',
            'hero-cinematic-aurora' => 'cinematic_scroll',
            'stats-section' => 'statistics',
            'testimonial-section' => 'testimonials',
            'gallery-section' => 'gallery',
            'staff-grid' => 'team_directory',
            'admission-steps' => 'admissions_block',
            'event-list-grid' => 'events_calendar',
            'contact-form-map' => 'contact_map',
            'cta-banner' => 'cta_banner',
            'facilities-grid' => 'features_grid',
            'news-featured-hero' => 'dynamic_news',
        ];

        return $map[$specKey] ?? str_replace('-', '_', $specKey);
    }

    public static function specKey(string $type): string
    {
        return str_replace('_', '-', $type);
    }

    /**
     * Full catalog: component key -> definition. Rich enough that the page
     * builder can auto-generate a grouped edit form without per-block UI.
     */
    public static function catalog(): array
    {
        if (self::$catalog !== null) {
            return self::$catalog;
        }

        $image = fn (string $placeholderKey, string $group = self::GROUP_CONTENT) => [
            'type' => 'image', 'group' => $group, 'placeholder' => $placeholderKey,
        ];
        $list = fn (array $itemFields, array $extra = []) => array_merge([
            'type' => 'list', 'items' => $itemFields,
        ], $extra);

        self::$catalog = [
            // ───────────────────────────── Reference-derived interactive ────
            'coverflow_carousel' => [
                'name' => 'Coverflow Carousel',
                'spec' => 'coverflow-carousel',
                'category' => 'Interactive',
                'description' => 'Active card centered upright, neighbours receding in 3D perspective; click or arrow-key to focus.',
                'default_variant' => 'classic',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'subtitle' => ['type' => 'textarea', 'label' => 'Subheading', 'group' => self::GROUP_CONTENT],
                    'slides' => ['type' => 'image_list', 'group' => self::GROUP_CONTENT, 'item_schema' => ['image', 'title'], 'max' => 12],
                    'card_width' => ['type' => 'number', 'label' => 'Card width (px)', 'group' => self::GROUP_LAYOUT, 'default' => 380, 'min' => 240, 'max' => 640, 'step' => 10],
                    'card_height' => ['type' => 'number', 'label' => 'Card height (px)', 'group' => self::GROUP_LAYOUT, 'default' => 300, 'min' => 180, 'max' => 640, 'step' => 10],
                    'radius' => ['type' => 'range', 'label' => 'Card corner radius', 'group' => self::GROUP_APPEARANCE, 'default' => 12, 'min' => 0, 'max' => 60, 'step' => 2],
                    'tilt' => ['type' => 'range', 'label' => 'Side tilt (deg)', 'group' => self::GROUP_APPEARANCE, 'default' => 12, 'min' => 0, 'max' => 40, 'step' => 1],
                    'gap' => ['type' => 'range', 'label' => 'Card spacing', 'group' => self::GROUP_LAYOUT, 'default' => 8, 'min' => 2, 'max' => 24, 'step' => 1],
                    'opacity' => ['type' => 'range', 'label' => 'Inactive dim (%)', 'group' => self::GROUP_APPEARANCE, 'default' => 60, 'min' => 0, 'max' => 100, 'step' => 5],
                    'autoplay' => ['type' => 'toggle', 'label' => 'Autoplay', 'group' => self::GROUP_ANIMATION, 'default' => false],
                    'autoplay_direction' => ['type' => 'select', 'label' => 'Autoplay direction', 'group' => self::GROUP_ANIMATION, 'default' => 'rightToLeft', 'options' => ['rightToLeft' => 'Right to left', 'leftToRight' => 'Left to right']],
                    'transition_duration' => ['type' => 'range', 'label' => 'Transition (s)', 'group' => self::GROUP_ANIMATION, 'default' => 0.6, 'min' => 0.2, 'max' => 2, 'step' => 0.1],
                    'transition_delay' => ['type' => 'range', 'label' => 'Autoplay delay (s)', 'group' => self::GROUP_ANIMATION, 'default' => 2.5, 'min' => 0.5, 'max' => 8, 'step' => 0.1],
                    'show_title' => ['type' => 'toggle', 'label' => 'Show slide titles', 'group' => self::GROUP_APPEARANCE, 'default' => true],
                    'title_position' => ['type' => 'select', 'label' => 'Title corner', 'group' => self::GROUP_APPEARANCE, 'default' => 'bottomLeft', 'options' => ['bottomLeft' => 'Bottom left', 'bottomRight' => 'Bottom right', 'topLeft' => 'Top left', 'topRight' => 'Top right']],
                    'title_color' => ['type' => 'color', 'label' => 'Title color', 'group' => self::GROUP_APPEARANCE, 'default' => '#ffffff'],
                    'reduced_motion' => ['type' => 'toggle', 'label' => 'Honor reduced motion (auto-static)', 'group' => self::GROUP_RESPONSIVE, 'default' => true],
                ],
            ],

            'orbit_gallery' => [
                'name' => 'Orbit Gallery',
                'spec' => 'orbit-gallery',
                'category' => 'Interactive',
                'description' => 'Images arranged on a tilted elliptical orbit, slowly auto-rotating.',
                'default_variant' => 'ellipse',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'subtitle' => ['type' => 'textarea', 'label' => 'Subheading', 'group' => self::GROUP_CONTENT],
                    'center_label' => ['type' => 'text', 'label' => 'Center label', 'group' => self::GROUP_CONTENT, 'default' => 'Pillars'],
                    'images' => ['type' => 'image_list', 'group' => self::GROUP_CONTENT, 'item_schema' => ['image', 'label'], 'max' => 12],
                    'item_size' => ['type' => 'range', 'label' => 'Item size (px)', 'group' => self::GROUP_LAYOUT, 'default' => 84, 'min' => 48, 'max' => 160, 'step' => 4],
                    'orbit_radius_x' => ['type' => 'range', 'label' => 'Orbit width (px)', 'group' => self::GROUP_LAYOUT, 'default' => 180, 'min' => 80, 'max' => 420, 'step' => 10],
                    'orbit_radius_y' => ['type' => 'range', 'label' => 'Orbit height (px)', 'group' => self::GROUP_LAYOUT, 'default' => 70, 'min' => 30, 'max' => 200, 'step' => 5],
                    'rotation_speed' => ['type' => 'range', 'label' => 'Rotation speed (deg/s)', 'group' => self::GROUP_ANIMATION, 'default' => 6, 'min' => 0, 'max' => 30, 'step' => 1],
                    'direction' => ['type' => 'select', 'label' => 'Direction', 'group' => self::GROUP_ANIMATION, 'default' => 'clockwise', 'options' => ['clockwise' => 'Clockwise', 'counter_clockwise' => 'Counter-clockwise']],
                    'tilt' => ['type' => 'range', 'label' => 'Perspective tilt (deg)', 'group' => self::GROUP_APPEARANCE, 'default' => 18, 'min' => 0, 'max' => 40, 'step' => 1],
                ],
            ],

            'marquee_ticker' => [
                'name' => 'Marquee Ticker',
                'spec' => 'marquee-ticker',
                'category' => 'Interactive',
                'description' => 'Continuous scrolling strip of achievements, announcements or photo highlights with edge-fading mask.',
                'default_variant' => 'two-row',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'items' => ['type' => 'list', 'group' => self::GROUP_CONTENT, 'items' => [['label' => 'text']]],
                    'speed' => ['type' => 'range', 'label' => 'Scroll speed (s per cycle)', 'group' => self::GROUP_ANIMATION, 'default' => 25, 'min' => 6, 'max' => 90, 'step' => 1],
                    'direction' => ['type' => 'select', 'label' => 'Direction', 'group' => self::GROUP_ANIMATION, 'default' => 'rightToLeft', 'options' => ['rightToLeft' => 'Right to left', 'leftToRight' => 'Left to right']],
                    'fade_intensity' => ['type' => 'range', 'label' => 'Edge fade (%)', 'group' => self::GROUP_APPEARANCE, 'default' => 18, 'min' => 0, 'max' => 45, 'step' => 1],
                    'separator' => ['type' => 'text', 'label' => 'Item separator', 'group' => self::GROUP_APPEARANCE, 'default' => '✦'],
                ],
            ],

            'kinetic_reveal_heading' => [
                'name' => 'Kinetic Reveal Heading',
                'spec' => 'kinetic-reveal-heading',
                'category' => 'Interactive',
                'description' => 'Words animate in with a soft diffuse entrance, triggered on scroll/hover.',
                'default_variant' => 'smoke',
                'props' => [
                    'text' => ['type' => 'textarea', 'label' => 'Heading text', 'group' => self::GROUP_CONTENT],
                    'trigger' => ['type' => 'select', 'label' => 'Trigger', 'group' => self::GROUP_ANIMATION, 'default' => 'scroll', 'options' => ['scroll' => 'On scroll', 'hover' => 'On hover', 'load' => 'On load']],
                    'intensity' => ['type' => 'range', 'label' => 'Smoke intensity', 'group' => self::GROUP_ANIMATION, 'default' => 1, 'min' => 0.2, 'max' => 2, 'step' => 0.1],
                    'title_size' => ['type' => 'number', 'label' => 'Font size (px)', 'group' => self::GROUP_APPEARANCE, 'default' => 56, 'min' => 24, 'max' => 160, 'step' => 2],
                ],
            ],

            'scroll_highlight_text' => [
                'name' => 'Scroll Highlight Text',
                'spec' => 'scroll-highlight-text',
                'category' => 'Interactive',
                'description' => 'Paragraph dims by default; words light up progressively as the section scrolls through the viewport.',
                'default_variant' => 'word',
                'props' => [
                    'text' => ['type' => 'textarea', 'label' => 'Body text', 'group' => self::GROUP_CONTENT],
                    'dim_color' => ['type' => 'color', 'label' => 'Dim color', 'group' => self::GROUP_APPEARANCE, 'default' => ''],
                    'highlight_color' => ['type' => 'color', 'label' => 'Highlight color', 'group' => self::GROUP_APPEARANCE, 'default' => ''],
                    'split_by' => ['type' => 'select', 'label' => 'Split by', 'group' => self::GROUP_ANIMATION, 'default' => 'word', 'options' => ['word' => 'Word', 'character' => 'Character']],
                ],
            ],

            'depth_text' => [
                'name' => 'Depth Text',
                'spec' => 'depth-text',
                'category' => 'Interactive',
                'description' => 'Layered 3D display text with pointer tilt and gentle auto-orbit. Use sparingly — premium moments only.',
                'default_variant' => 'layered',
                'props' => [
                    'text' => ['type' => 'text', 'label' => 'Text', 'group' => self::GROUP_CONTENT],
                    'layers' => ['type' => 'range', 'label' => 'Layers', 'group' => self::GROUP_APPEARANCE, 'default' => 4, 'min' => 2, 'max' => 8, 'step' => 1],
                    'step' => ['type' => 'range', 'label' => 'Layer depth', 'group' => self::GROUP_APPEARANCE, 'default' => 2.5, 'min' => 1, 'max' => 8, 'step' => 0.1],
                    'pointer_tracking' => ['type' => 'toggle', 'label' => 'Pointer tracking', 'group' => self::GROUP_ANIMATION, 'default' => true],
                    'auto_orbit' => ['type' => 'toggle', 'label' => 'Auto orbit', 'group' => self::GROUP_ANIMATION, 'default' => true],
                    'title_size' => ['type' => 'number', 'label' => 'Font size (px)', 'group' => self::GROUP_APPEARANCE, 'default' => 72, 'min' => 24, 'max' => 200, 'step' => 2],
                ],
            ],

            'stat_globe' => [
                'name' => 'Global Community Globe',
                'spec' => 'stat-globe',
                'category' => 'Interactive',
                'description' => 'Interactive rotating globe with alumni-by-country markers. Heaviest block — optional per template.',
                'default_variant' => 'webgl',
                'heavy' => true,
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'subtitle' => ['type' => 'textarea', 'label' => 'Subheading', 'group' => self::GROUP_CONTENT],
                    'markers' => ['type' => 'list', 'group' => self::GROUP_CONTENT, 'items' => [['label' => 'text'], ['lat' => 'number'], ['lng' => 'number']]],
                    'rotation_speed' => ['type' => 'range', 'label' => 'Rotation speed', 'group' => self::GROUP_ANIMATION, 'default' => 1, 'min' => 0, 'max' => 4, 'step' => 0.1],
                    'marker_color' => ['type' => 'color', 'label' => 'Marker color', 'group' => self::GROUP_APPEARANCE, 'default' => '#06b6d4'],
                    'drag' => ['type' => 'toggle', 'label' => 'Draggable', 'group' => self::GROUP_ANIMATION, 'default' => true],
                ],
            ],

            // ───────────────────────────── Structural / plain components ────
            'hero' => [
                'name' => 'Hero',
                'category' => 'Hero',
                'default_variant' => 'hero-premium',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Headline', 'group' => self::GROUP_CONTENT],
                    'badge_text' => ['type' => 'text', 'label' => 'Badge text (defaults to enrollment year)', 'group' => self::GROUP_CONTENT, 'default' => ''],
                    'description' => ['type' => 'rich_text', 'label' => 'Lead text', 'group' => self::GROUP_CONTENT, 'default' => 'A premier educational institution guiding next-generation achievements.'],
                    'cta_text' => ['type' => 'text', 'label' => 'Primary button label', 'group' => self::GROUP_CONTENT],
                    'cta_url' => ['type' => 'url', 'label' => 'Primary button link', 'group' => self::GROUP_CONTENT],
                    'secondary_cta_text' => ['type' => 'text', 'label' => 'Secondary button label', 'group' => self::GROUP_CONTENT],
                    'secondary_cta_url' => ['type' => 'url', 'label' => 'Secondary button link', 'group' => self::GROUP_CONTENT],
                    'image_url' => $image('campus-exterior'),
                    'layout' => ['type' => 'select', 'label' => 'Image position', 'group' => self::GROUP_LAYOUT, 'default' => 'image-right', 'options' => ['image-right' => 'Image right', 'image-left' => 'Image left', 'centered' => 'Centered', 'full-bleed' => 'Full bleed background']],
                    'image_fit' => ['type' => 'select', 'label' => 'Image fit', 'group' => self::GROUP_LAYOUT, 'default' => 'cover', 'options' => ['cover' => 'Cover', 'contain' => 'Contain']],
                    'image_position' => ['type' => 'select', 'label' => 'Image position', 'group' => self::GROUP_LAYOUT, 'default' => 'center', 'options' => ['top' => 'Top', 'center' => 'Center', 'bottom' => 'Bottom', 'left' => 'Left', 'right' => 'Right']],
                    'use_depth_text' => ['type' => 'toggle', 'label' => 'DepthText headline (premium)', 'group' => self::GROUP_ANIMATION, 'default' => false],
                ],
            ],

            'statistics' => [
                'name' => 'Statistics',
                'spec' => 'stats-section',
                'category' => 'Evidence',
                'default_variant' => 'large-number',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'subtitle' => ['type' => 'textarea', 'label' => 'Subheading', 'group' => self::GROUP_CONTENT],
                    'source' => ['type' => 'select', 'label' => 'Data source', 'group' => self::GROUP_CONTENT, 'default' => 'live', 'options' => ['live' => 'Live module counts', 'manual' => 'Manual numbers']],
                    'items' => ['type' => 'list', 'group' => self::GROUP_CONTENT, 'items' => [['label' => 'text'], ['value' => 'number'], ['suffix' => 'text']]],
                ],
            ],

            'testimonials' => [
                'name' => 'Testimonials',
                'spec' => 'testimonial-section',
                'category' => 'Evidence',
                'default_variant' => 'large-quote',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'subtitle' => ['type' => 'textarea', 'label' => 'Subheading', 'group' => self::GROUP_CONTENT],
                    'testimonials' => ['type' => 'list', 'group' => self::GROUP_CONTENT, 'items' => [['quote' => 'textarea'], ['name' => 'text'], ['role' => 'text'], ['image' => 'image']]],
                ],
            ],

            'gallery' => [
                'name' => 'Gallery',
                'spec' => 'gallery-section',
                'category' => 'Media',
                'default_variant' => 'masonry',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'subtitle' => ['type' => 'textarea', 'label' => 'Subheading', 'group' => self::GROUP_CONTENT],
                    'columns' => ['type' => 'range', 'label' => 'Columns', 'group' => self::GROUP_LAYOUT, 'default' => 3, 'min' => 1, 'max' => 6, 'step' => 1],
                    'images' => ['type' => 'image_list', 'group' => self::GROUP_CONTENT, 'item_schema' => ['image', 'caption'], 'max' => 24],
                ],
            ],

            'team_directory' => [
                'name' => 'Staff Directory',
                'spec' => 'staff-grid',
                'category' => 'People',
                'default_variant' => 'grid-editorial',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'subtitle' => ['type' => 'textarea', 'label' => 'Subheading', 'group' => self::GROUP_CONTENT],
                    'source' => ['type' => 'select', 'label' => 'Data source', 'group' => self::GROUP_CONTENT, 'default' => 'live', 'options' => ['live' => 'Staff module', 'manual' => 'Manual entries']],
                    'members' => ['type' => 'list', 'group' => self::GROUP_CONTENT, 'items' => [['name' => 'text'], ['role' => 'text'], ['bio' => 'textarea'], ['image' => 'image']]],
                ],
            ],

            'cta_banner' => [
                'name' => 'Call to Action',
                'spec' => 'cta-banner',
                'category' => 'Conversion',
                'default_variant' => 'centered-solid',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Headline', 'group' => self::GROUP_CONTENT],
                    'description' => ['type' => 'rich_text', 'label' => 'Supporting text', 'group' => self::GROUP_CONTENT],
                    'cta_text' => ['type' => 'text', 'label' => 'Button label', 'group' => self::GROUP_CONTENT],
                    'cta_url' => ['type' => 'url', 'label' => 'Button link', 'group' => self::GROUP_CONTENT],
                    'image_url' => $image('campus-quad'),
                ],
            ],

            'contact_map' => [
                'name' => 'Contact / Map',
                'spec' => 'contact-form-map',
                'category' => 'Conversion',
                'default_variant' => 'split-form',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'description' => ['type' => 'rich_text', 'label' => 'Supporting text', 'group' => self::GROUP_CONTENT],
                    'address' => ['type' => 'textarea', 'label' => 'Address', 'group' => self::GROUP_CONTENT],
                    'phone' => ['type' => 'text', 'label' => 'Phone', 'group' => self::GROUP_CONTENT],
                    'email' => ['type' => 'text', 'label' => 'Email', 'group' => self::GROUP_CONTENT],
                    'map_url' => ['type' => 'url', 'label' => 'Embed map URL', 'group' => self::GROUP_CONTENT],
                    'hours' => ['type' => 'textarea', 'label' => 'Office hours', 'group' => self::GROUP_CONTENT],
                ],
            ],

            'dynamic_news' => [
                'name' => 'News Feed',
                'spec' => 'news-featured-hero',
                'category' => 'Dynamic',
                'default_variant' => 'featured-hero',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'subtitle' => ['type' => 'textarea', 'label' => 'Subheading', 'group' => self::GROUP_CONTENT],
                    'limit' => ['type' => 'number', 'label' => 'Items shown', 'group' => self::GROUP_CONTENT, 'default' => 6, 'min' => 1, 'max' => 24, 'step' => 1],
                    'source' => ['type' => 'select', 'label' => 'Data source', 'group' => self::GROUP_CONTENT, 'default' => 'live', 'options' => ['live' => 'Announcements module', 'manual' => 'Manual entries']],
                    'items' => ['type' => 'list', 'group' => self::GROUP_CONTENT, 'items' => [['title' => 'text'], ['excerpt' => 'textarea'], ['image' => 'image'], ['date' => 'text']]],
                ],
            ],

            'events_calendar' => [
                'name' => 'Events Calendar',
                'spec' => 'event-list-grid',
                'category' => 'Dynamic',
                'default_variant' => 'agenda-list',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'subtitle' => ['type' => 'textarea', 'label' => 'Subheading', 'group' => self::GROUP_CONTENT],
                    'limit' => ['type' => 'number', 'label' => 'Items shown', 'group' => self::GROUP_CONTENT, 'default' => 6, 'min' => 1, 'max' => 24, 'step' => 1],
                    'source' => ['type' => 'select', 'label' => 'Data source', 'group' => self::GROUP_CONTENT, 'default' => 'live', 'options' => ['live' => 'Events module', 'manual' => 'Manual entries']],
                    'items' => ['type' => 'list', 'group' => self::GROUP_CONTENT, 'items' => [['title' => 'text'], ['date' => 'text'], ['location' => 'text'], ['description' => 'textarea']]],
                ],
            ],

            'admissions_block' => [
                'name' => 'Admissions Steps',
                'spec' => 'admission-steps',
                'category' => 'Admissions',
                'default_variant' => 'steps-timeline',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'subtitle' => ['type' => 'textarea', 'label' => 'Subheading', 'group' => self::GROUP_CONTENT],
                    'show_form' => ['type' => 'toggle', 'label' => 'Show application form', 'group' => self::GROUP_CONTENT, 'default' => true],
                    'steps' => ['type' => 'list', 'group' => self::GROUP_CONTENT, 'items' => [['title' => 'text'], ['description' => 'textarea']]],
                    'documents' => ['type' => 'list', 'group' => self::GROUP_CONTENT, 'items' => [['label' => 'text']]],
                    'fee_note' => ['type' => 'rich_text', 'label' => 'Fees enquiry note', 'group' => self::GROUP_CONTENT],
                    'bg_color' => ['type' => 'color', 'label' => 'Background Color', 'group' => self::GROUP_APPEARANCE],
                    'bg_image' => ['type' => 'image', 'label' => 'Background Image', 'group' => self::GROUP_APPEARANCE],
                ],
            ],

            'features_grid' => [
                'name' => 'Facilities Grid',
                'spec' => 'facilities-grid',
                'category' => 'Content',
                'default_variant' => 'cards',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'subtitle' => ['type' => 'textarea', 'label' => 'Subheading', 'group' => self::GROUP_CONTENT],
                    'features' => ['type' => 'list', 'group' => self::GROUP_CONTENT, 'items' => [['title' => 'text'], ['desc' => 'textarea'], ['image' => 'image']]],
                ],
            ],

            'academics_grid' => [
                'name' => 'Academic Faculties',
                'category' => 'Content',
                'default_variant' => 'cards',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'items' => ['type' => 'list', 'group' => self::GROUP_CONTENT, 'items' => [['title' => 'text'], ['desc' => 'textarea']]],
                ],
            ],

            'about_section' => [
                'name' => 'About Section',
                'category' => 'Content',
                'default_variant' => 'editorial',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'description' => ['type' => 'rich_text', 'label' => 'Description', 'group' => self::GROUP_CONTENT],
                    'mission' => ['type' => 'rich_text', 'label' => 'Mission statement', 'group' => self::GROUP_CONTENT],
                    'vision' => ['type' => 'rich_text', 'label' => 'Vision statement', 'group' => self::GROUP_CONTENT],
                    'image_url' => $image('campus-quad'),
                ],
            ],

            'principal_welcome' => [
                'name' => 'Principal Welcome',
                'category' => 'Content',
                'default_variant' => 'split',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'principal_name' => ['type' => 'text', 'label' => 'Principal name', 'group' => self::GROUP_CONTENT],
                    'principal_title' => ['type' => 'text', 'label' => 'Principal title', 'group' => self::GROUP_CONTENT],
                    'description' => ['type' => 'rich_text', 'label' => 'Welcome message', 'group' => self::GROUP_CONTENT],
                    'image_url' => $image('staff-silhouette'),
                ],
            ],

            'faq_accordion' => [
                'name' => 'FAQ Accordion',
                'category' => 'Content',
                'default_variant' => 'accordion',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'faqs' => ['type' => 'list', 'group' => self::GROUP_CONTENT, 'items' => [['q' => 'text'], ['a' => 'textarea']]],
                ],
            ],

            'logo_cloud' => [
                'name' => 'Logo Cloud',
                'category' => 'Content',
                'default_variant' => 'cloud',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'logos' => ['type' => 'list', 'group' => self::GROUP_CONTENT, 'items' => [['name' => 'text'], ['logo_url' => 'image']]],
                ],
            ],

            'video_embed' => [
                'name' => 'Video Embed',
                'category' => 'Media',
                'default_variant' => 'embed',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Heading', 'group' => self::GROUP_CONTENT],
                    'video_url' => ['type' => 'url', 'label' => 'Video URL', 'group' => self::GROUP_CONTENT],
                ],
            ],

            'cinematic_scroll' => [
                'name' => 'Living Aurora Hero',
                'spec' => 'hero-cinematic-aurora',
                'category' => 'Interactive',
                'description' => 'Full-bleed canvas aurora of organic gradient light that breathes, drifts with the pointer and reacts to scroll. The signature cinematic showpiece — replaces the legacy frame-sequence scrub.',
                'default_variant' => 'aurora-immersive',
                'props' => [
                    'title' => ['type' => 'text', 'label' => 'Headline', 'group' => self::GROUP_CONTENT],
                    'subtitle' => ['type' => 'textarea', 'label' => 'Subheadline', 'group' => self::GROUP_CONTENT],
                    'primary_cta_text' => ['type' => 'text', 'label' => 'Primary button label', 'group' => self::GROUP_CONTENT],
                    'primary_cta_url' => ['type' => 'url', 'label' => 'Primary button link', 'group' => self::GROUP_CONTENT],
                    'secondary_cta_text' => ['type' => 'text', 'label' => 'Secondary button label', 'group' => self::GROUP_CONTENT],
                    'secondary_cta_url' => ['type' => 'url', 'label' => 'Secondary button link', 'group' => self::GROUP_CONTENT],
                    'hue_shift' => ['type' => 'toggle', 'label' => 'Slow hue shift', 'group' => self::GROUP_ANIMATION, 'default' => true],
                    'blob_count' => ['type' => 'range', 'label' => 'Aurora blobs', 'group' => self::GROUP_APPEARANCE, 'default' => 4, 'min' => 2, 'max' => 8, 'step' => 1],
                    'intensity' => ['type' => 'range', 'label' => 'Glow intensity', 'group' => self::GROUP_APPEARANCE, 'default' => 0.55, 'min' => 0.1, 'max' => 1, 'step' => 0.05],
                    'speed' => ['type' => 'range', 'label' => 'Drift speed', 'group' => self::GROUP_ANIMATION, 'default' => 1, 'min' => 0.1, 'max' => 3, 'step' => 0.1],
                    'scroll_reaction' => ['type' => 'toggle', 'label' => 'React to scroll', 'group' => self::GROUP_ANIMATION, 'default' => true],
                    'pointer_reaction' => ['type' => 'toggle', 'label' => 'Drift with pointer', 'group' => self::GROUP_ANIMATION, 'default' => true],
                    'show_chips' => ['type' => 'toggle', 'label' => 'Floating stat chips', 'group' => self::GROUP_APPEARANCE, 'default' => true],
                    'show_progress' => ['type' => 'toggle', 'label' => 'Scroll progress indicator', 'group' => self::GROUP_APPEARANCE, 'default' => true],
                ],
            ],

            'divider' => [
                'name' => 'Divider / Spacer',
                'category' => 'Layout',
                'default_variant' => 'default',
                'props' => [
                    'height' => ['type' => 'range', 'label' => 'Spacer height (px)', 'group' => self::GROUP_LAYOUT, 'default' => 48, 'min' => 8, 'max' => 200, 'step' => 4],
                    'bg_color' => ['type' => 'color', 'label' => 'Background Color', 'group' => self::GROUP_APPEARANCE],
                ],
            ],
        ];

        return self::$catalog;
    }

    /**
     * Variant catalog: component key -> variant_key -> presentation config.
     * template_origin records which system template first shipped a variant
     * (picker attribution only — never restricts usage).
     */
    public static function variants(): array
    {
        if (self::$variants !== null) {
            return self::$variants;
        }

        $v = fn (string $key, string $variant, string $name, string $origin, array $config = []) => [
            'variant_key' => $variant, 'name' => $name, 'template_origin' => $origin, 'config' => $config,
        ];

        self::$variants = [
            'hero' => [
                $v('hero', 'hero-premium', 'Premium Split', 'heritage-editorial'),
                $v('hero', 'hero-editorial', 'Editorial Ledger', 'heritage-editorial', ['texture' => 'paper']),
                $v('hero', 'hero-cinematic', 'Cinematic Overlay', 'cinematic-immersive', ['overlay' => 'bottom-gradient']),
                $v('hero', 'hero-modern', 'Modern Split', 'modern-vibrant', ['shapes' => true]),
                $v('hero', 'hero-minimal', 'Minimal Typographic', 'minimalist-academic', ['motion' => 'type-only']),
            ],
            'statistics' => [
                $v('statistics', 'large-number', 'Large Number', 'cinematic-immersive'),
                $v('statistics', 'minimal-editorial', 'Minimal Editorial', 'heritage-editorial'),
                $v('statistics', 'cinematic-overlay', 'Cinematic Overlay', 'cinematic-immersive'),
                $v('statistics', 'horizontal-marquee', 'Horizontal Marquee', 'modern-vibrant'),
            ],
            'testimonials' => [
                $v('testimonials', 'large-quote', 'Large Quote', 'heritage-editorial'),
                $v('testimonials', 'split-editorial', 'Split Editorial', 'minimalist-academic'),
                $v('testimonials', 'carousel', 'Carousel', 'modern-vibrant'),
                $v('testimonials', 'image-led', 'Image Led', 'community-warm'),
            ],
            'gallery' => [
                $v('gallery', 'masonry', 'Masonry', 'modern-vibrant'),
                $v('gallery', 'horizontal-scroll', 'Horizontal Scroll', 'cinematic-immersive'),
                $v('gallery', 'immersive-grid', 'Immersive Grid', 'community-warm'),
                $v('gallery', 'featured-image', 'Featured Image', 'heritage-editorial'),
            ],
            'team_directory' => [
                $v('team_directory', 'grid-editorial', 'Editorial Grid', 'heritage-editorial'),
                $v('team_directory', 'circle-photos', 'Circle Photos', 'community-warm'),
                $v('team_directory', 'directory-table', 'Directory Table', 'minimalist-academic'),
            ],
            'cta_banner' => [
                $v('cta_banner', 'centered-solid', 'Centered Solid', 'heritage-editorial'),
                $v('cta_banner', 'split-panel', 'Split Panel', 'modern-vibrant'),
                $v('cta_banner', 'full-bleed', 'Full Bleed', 'cinematic-immersive'),
            ],
            'contact_map' => [
                $v('contact_map', 'split-form', 'Split Form', 'heritage-editorial'),
                $v('contact_map', 'centered-form', 'Centered Form', 'minimalist-academic'),
                $v('contact_map', 'map-led', 'Map Led', 'modern-vibrant'),
            ],
            'dynamic_news' => [
                $v('dynamic_news', 'featured-hero', 'Featured Hero', 'heritage-editorial'),
                $v('dynamic_news', 'list-editorial', 'List Editorial', 'minimalist-academic'),
            ],
            'events_calendar' => [
                $v('events_calendar', 'agenda-list', 'Agenda List', 'heritage-editorial'),
                $v('events_calendar', 'timeline', 'Timeline', 'minimalist-academic'),
                $v('events_calendar', 'mini-grid', 'Mini Grid', 'modern-vibrant'),
            ],
            'admissions_block' => [
                $v('admissions_block', 'steps-timeline', 'Steps Timeline', 'heritage-editorial'),
                $v('admissions_block', 'panels', 'Panels', 'modern-vibrant'),
                $v('admissions_block', 'checklist', 'Checklist', 'minimalist-academic'),
            ],
            'features_grid' => [
                $v('features_grid', 'cards', 'Cards', 'modern-vibrant'),
                $v('features_grid', 'icon-list', 'Icon List', 'minimalist-academic'),
                $v('features_grid', 'split-feature', 'Split Feature', 'heritage-editorial'),
            ],
            'academics_grid' => [
                $v('academics_grid', 'cards', 'Cards', 'modern-vibrant'),
                $v('academics_grid', 'numbered', 'Numbered', 'heritage-editorial'),
            ],
            'about_section' => [
                $v('about_section', 'editorial', 'Editorial', 'heritage-editorial'),
                $v('about_section', 'split', 'Split', 'modern-vibrant'),
                $v('about_section', 'timeline', 'Timeline', 'minimalist-academic'),
            ],
            'coverflow_carousel' => [
                $v('coverflow_carousel', 'classic', 'Classic Coverflow', 'modern-vibrant'),
                $v('coverflow_carousel', 'editorial', 'Editorial Coverflow', 'heritage-editorial'),
            ],
            'orbit_gallery' => [
                $v('orbit_gallery', 'ellipse', 'Elliptical Orbit', 'community-warm'),
                $v('orbit_gallery', 'circle', 'Circle Orbit', 'modern-vibrant'),
            ],
            'marquee_ticker' => [
                $v('marquee_ticker', 'two-row', 'Two Row Ticker', 'modern-vibrant'),
                $v('marquee_ticker', 'single-row', 'Single Row Ticker', 'heritage-editorial'),
            ],
            'kinetic_reveal_heading' => [
                $v('kinetic_reveal_heading', 'smoke', 'Smoke Reveal', 'cinematic-immersive'),
                $v('kinetic_reveal_heading', 'rise', 'Rise', 'modern-vibrant'),
            ],
            'scroll_highlight_text' => [
                $v('scroll_highlight_text', 'word', 'Word Highlight', 'minimalist-academic'),
                $v('scroll_highlight_text', 'character', 'Character Highlight', 'cinematic-immersive'),
            ],
            'depth_text' => [
                $v('depth_text', 'layered', 'Layered 3D', 'cinematic-immersive'),
            ],
            'stat_globe' => [
                $v('stat_globe', 'webgl', 'WebGL Globe', 'community-warm'),
            ],
            'cinematic_scroll' => [
                $v('cinematic_scroll', 'aurora-immersive', 'Immersive Aurora', 'cinematic-immersive', ['blob_count' => 4, 'intensity' => 0.55, 'speed' => 1, 'scroll_reaction' => true, 'pointer_reaction' => true]),
                $v('cinematic_scroll', 'aurora-tranquil', 'Tranquil Aurora', 'minimalist-academic', ['blob_count' => 3, 'intensity' => 0.35, 'speed' => 0.6, 'scroll_reaction' => false, 'pointer_reaction' => true]),
                $v('cinematic_scroll', 'aurora-vibrant', 'Vibrant Aurora', 'modern-vibrant', ['blob_count' => 6, 'intensity' => 0.8, 'speed' => 1.6, 'scroll_reaction' => true, 'pointer_reaction' => true]),
            ],
        ];

        return self::$variants;
    }

    public static function component(string $type): ?array
    {
        return self::catalog()[$type] ?? null;
    }

    public static function variantsFor(string $type): array
    {
        $def = self::component($type);

        return self::variants()[$type] ?? [
            ['variant_key' => $def['default_variant'] ?? 'default', 'name' => $def['name'] ?? ucwords(str_replace('_', ' ', $type)), 'template_origin' => null, 'config' => []],
        ];
    }

    public static function defaultVariant(string $type): string
    {
        return self::component($type)['default_variant'] ?? 'default';
    }

    public static function hasVariant(string $type, ?string $variant): bool
    {
        if ($variant === null || $variant === '') {
            return true;
        }

        return collect(self::variantsFor($type))->contains('variant_key', $variant);
    }

    public static function safeVariant(string $type, ?string $variant): string
    {
        return self::hasVariant($type, $variant) ? ($variant ?: self::defaultVariant($type)) : self::defaultVariant($type);
    }

    /** Merge registry defaults (defaults + variant-aware overrides) into a block. */
    public static function normalizeBlock(array $block): array
    {
        $type = $block['type'] ?? '';
        $def = self::component($type);
        if ($def === null) {
            return $block;
        }

        $variant = self::safeVariant($type, $block['variant'] ?? null);
        $block['variant'] = $variant;

        $defaults = [];
        foreach ($def['props'] as $key => $field) {
            if (array_key_exists('default', $field)) {
                $defaults[$key] = $field['default'];
            }
        }

        // Variant-specific config overrides (from variant.config) applied last.
        foreach (self::variantsFor($type) as $vc) {
            if ($vc['variant_key'] === $variant && ! empty($vc['config'])) {
                $defaults = array_replace($defaults, $vc['config']);
            }
        }

        // Merge without clobbering styles/ids or stored props.
        foreach ($defaults as $key => $value) {
            if (! array_key_exists($key, $block)) {
                $block[$key] = $value;
            }
        }

        return $block;
    }

    public static function categories(): array
    {
        return collect(self::catalog())->map(fn ($c) => $c['category'])->unique()->values()->all();
    }

    /** Blocks available for the cross-template "add block" picker, grouped. */
    public static function pickerOptions(?string $category = null): array
    {
        $catalog = collect(self::catalog());
        if ($category) {
            $catalog = $catalog->where('category', $category);
        }

        return $catalog
            ->map(fn ($def, $type) => [
                'type' => $type,
                'name' => $def['name'],
                'spec' => $def['spec'] ?? self::specKey($type),
                'category' => $def['category'],
                'description' => $def['description'] ?? '',
                'variants' => collect(self::variantsFor($type))->pluck('variant_key')->values()->all(),
            ])
            ->values()
            ->all();
    }
}
