<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
            font-size: 8px;
            color: #334155;
            margin: 0;
            padding: 0;
        }
        .header-table { width: 100%; padding-bottom: 8px; margin-bottom: 12px; border-bottom: 2px solid {{ $primaryColor }}; }
        .logo-box { width: 60px; vertical-align: middle; }
        .logo-box img { max-height: 50px; max-width: 50px; }
        .school-info { vertical-align: middle; padding-left: 8px; }
        .school-name { font-size: 14px; font-weight: bold; color: #0f172a; text-transform: uppercase; }
        .report-title { font-size: 14px; font-weight: bold; margin-bottom: 4px; text-transform: uppercase; text-align: center; color: {{ $primaryColor }}; }
        .meta-row { text-align: center; font-size: 8px; color: #64748b; margin-bottom: 10px; }
        .data-table { width: 100%; border-collapse: collapse; table-layout: auto; }
        .data-table th { color: #ffffff; font-weight: bold; text-align: left; padding: 5px 6px; border: 1px solid #e2e8f0; text-transform: uppercase; font-size: 8px; background-color: {{ $primaryColor }}; }
        .data-table td { padding: 4px 6px; border: 1px solid #cbd5e1; vertical-align: middle; font-size: 8px; word-break: break-word; }
        .data-table tr:nth-child(even) { background-color: #f8fafc; }
        .footer-table { width: 100%; border-top: 1px solid #cbd5e1; padding-top: 8px; margin-top: 16px; font-size: 7px; color: #94a3b8; }
    </style>
</head>
<body>

    <table class="header-table">
        <tr>
            @if ($school && ! empty($school->logo_path) && @file_get_contents(storage_path('app/public/'.$school->logo_path)))
                <td class="logo-box">
                    <img src="data:image/png;base64,{{ base64_encode(@file_get_contents(storage_path('app/public/'.$school->logo_path))) }}" alt="Logo">
                </td>
            @endif
            <td class="school-info">
                <div class="school-name">{{ $school->name ?? 'KAIRO DEMO ACADEMY' }}</div>
                <div class="meta-row" style="text-align:left;margin-bottom:0;">
                    {{ implode('  |  ', array_filter([
                        $school->physical_address ?? ($school->address ?? ''),
                        ($school->phone_number ?? '') ?: ($school->phone ?? ''),
                        $school->email_address ?? '',
                    ])) }}
                </div>
            </td>
            <td style="text-align: right; vertical-align: bottom; font-size: 7px; color: #64748b;">
                Date Run: {{ now()->format('Y-m-d H:i') }}<br>
                Records: {{ count($rows) }}
            </td>
        </tr>
    </table>

    <div class="report-title">{{ $title }}</div>
    <div class="meta-row">{{ $subtitle }}</div>

    <table class="data-table">
        <thead>
            <tr>
                @foreach ($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($row as $cell)
                        <td>{{ is_null($cell) || $cell === '' ? '-' : $cell }}</td>
                    @endforeach
                </tr>
            @empty
                <tr><td colspan="{{ count($headers) }}" style="text-align:center;color:#94a3b8;">{{ __('No records found.') }}</td></tr>
            @endforelse
        </tbody>
    </table>

    <table class="footer-table">
        <tr>
            <td>Generated by Kairo CORE • {{ config('app.name') }} • Confidential</td>
        </tr>
    </table>
</body>
</html>
