<?php

namespace App\Services\Csv;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Modules\Admin\Models\Department;
use Modules\Inventory\Models\ProcurementRequest;
use Modules\Inventory\Models\ProcurementRequestItem;

class ProcurementRequestCsvService extends CsvBulkService
{
    /**
     * Record types referenced from an uploaded file whose values may not exist
     * yet in the system. The import wizard shows a create-or-skip prompt for
     * every non-empty value that does not match an existing record.
     *
     * @return array<string, array{label: string, model: string, column: string}>
     */
    public static function referenceFields(): array
    {
        return [
            'department' => [
                'label' => __('Department'),
                'model' => Department::class,
                'column' => 'name',
            ],
        ];
    }

    public static function columns(): array
    {
        return [
            'department' => [
                'label' => __('Department'),
                'required' => false,
                'guesses' => ['Department'],
                'example' => 'Academics',
            ],
            'status' => [
                'label' => __('Status'),
                'required' => false,
                'guesses' => ['Status'],
                'example' => 'draft',
                'default' => 'draft',
                'in' => ['draft', 'pending_approval', 'approved', 'rejected'],
            ],
            'urgency' => [
                'label' => __('Urgency'),
                'required' => false,
                'guesses' => ['Urgency'],
                'example' => 'medium',
                'default' => 'medium',
                'in' => ['low', 'medium', 'high', 'emergency'],
            ],
            'item_names' => [
                'label' => __('Item Name(s)'),
                'required' => true,
                'guesses' => ['Item Name(s)', 'Items', 'Item Names', 'Item Name', 'Items Required'],
                'example' => 'A4 Paper; Printer Toner',
            ],
            'item_quantities' => [
                'label' => __('Item Quantity(ies)'),
                'required' => false,
                'guesses' => ['Item Quantity(ies)', 'Quantities', 'Quantity', 'Qty'],
                'example' => '10; 2',
            ],
            'estimated_unit_cost' => [
                'label' => __('Estimated Unit Cost'),
                'required' => false,
                'guesses' => ['Estimated Unit Cost', 'Unit Cost', 'Cost', 'Estimated Cost'],
                'example' => '5.50; 85.00',
            ],
            'purpose' => [
                'label' => __('Purpose'),
                'required' => false,
                'guesses' => ['Purpose'],
                'example' => 'Requisition for term one stationery.',
            ],
            'notes' => [
                'label' => __('Notes'),
                'required' => false,
                'guesses' => ['Notes'],
                'example' => 'Deliver to the admin block.',
            ],
        ];
    }

    /**
     * The procurement template carries no prefilled example row: request numbers
     * and requesters are generated by the system, and an example data row would
     * otherwise turn into a rejected/re-imported record.
     */
    public static function templateCsv(): string
    {
        $out = fopen('php://temp', 'r+');
        fwrite($out, "\xEF\xBB\xBF");
        fputcsv($out, static::exportHeaders());

        $examples = [
            ['Academics', 'draft', 'medium', 'A4 Paper; Printer Toner', '10; 2', '5.50; 85.00', 'Term 1 stationery requisition', 'Deliver to administration block'],
            ['Administration', 'pending_approval', 'high', 'Whiteboard Markers; Erasers', '5; 5', '2.00; 1.50', 'Staff room supplies', 'Urgent for meetings'],
            ['Science', 'draft', 'low', 'Test Tubes; Beakers; Bunsen Burner', '20; 10; 2', '1.20; 3.50; 25.00', 'Laboratory practicals', 'Handle with care'],
            ['Sports', 'approved', 'medium', 'Football; Whistles; Cones', '3; 4; 20', '25.00; 3.00; 0.50', 'Inter-house sports equipment', 'Store in PE equipment room'],
            ['Maintenance', 'draft', 'emergency', 'LED Bulbs; Door Hinges; Padlocks', '12; 6; 4', '4.50; 6.00; 12.00', 'Campus security and lighting repairs', 'Immediate replacement required'],
        ];

        foreach ($examples as $row) {
            fputcsv($out, $row);
        }

        rewind($out);
        $csv = stream_get_contents($out);
        fclose($out);

        return $csv;
    }

    public static function exportHeaders(): array
    {
        return [
            'Department', 'Status', 'Urgency', 'Item Name(s)', 'Item Quantity(ies)', 'Estimated Unit Cost', 'Purpose', 'Notes',
        ];
    }

    public static function exportRows(int $schoolId): iterable
    {
        $query = ProcurementRequest::withoutTenantScope()
            ->where('school_id', $schoolId)
            ->with(['items', 'requester'])
            ->orderBy('id');

        $lastId = 0;

        do {
            $requests = (clone $query)->where('id', '>', $lastId)->orderBy('id')->limit(500)->get();

            if ($requests->isEmpty()) {
                break;
            }

            foreach ($requests as $request) {
                $names = $request->items->map(fn ($item): string => $item->item_name)->implode('; ');
                $qtys = $request->items->map(fn ($item): string => $item->quantity)->implode('; ');
                $costs = $request->items->map(fn ($item): string => $item->estimated_unit_cost)->implode('; ');

                yield [
                    $request->department_id ? (Department::find($request->department_id)?->name ?? $request->department_id) : '',
                    $request->status,
                    $request->urgency,
                    $names,
                    $qtys,
                    $costs,
                    $request->purpose,
                    $request->notes,
                ];
            }

            $lastId = $requests->last()->id;
        } while (true);
    }

    /**
     * Split pipe / semicolon / newline separated values inside one CSV cell
     * into a list of individual items, quantities or costs.
     */
    protected static function splitValues(string $cell): array
    {
        $cell = trim($cell);

        if ($cell === '') {
            return [];
        }

        $parts = preg_split('/[;|\r\n]+/', $cell);

        return array_values(array_filter(array_map('trim', $parts ?: []), fn (string $part): bool => $part !== ''));
    }

    public static function import(string $filePath, int $schoolId, array $columnMap, ?callable $onProgress = null, array $options = []): array
    {
        $missingRefs = $options['missingRefs'] ?? [];

        $departmentIndex = [];
        Department::withoutTenantScope()
            ->where('school_id', $schoolId)
            ->get(['id', 'name'])
            ->each(function (Department $department) use (&$departmentIndex) {
                $departmentIndex[strtolower(trim($department->name))] = $department->id;
            });

        $existingCodes = Department::withoutTenantScope()
            ->where('school_id', $schoolId)
            ->pluck('code')
            ->flip();

        $lookups = [
            'departmentIndex' => $departmentIndex,
            'existingCodes' => $existingCodes,
            'missingRefs' => $missingRefs,
            'requesterId' => (int) ($options['requester_id'] ?? Auth::id()),
            'seq' => static::currentRequestSequence($schoolId),
            // Ordered list of department values in the file that do not
            // exist yet — mirrors the create-or-skip prompt from step 2.
            'unknownDepartments' => static::unknownReferenceValues($filePath, $schoolId, $columnMap, 'department'),
        ];

        return static::runImport(
            $filePath,
            $schoolId,
            $columnMap,
            $onProgress,
            $lookups,
            fn (array &$data, array $lookups) => static::validateAndNormalize($data, $lookups),
            fn (array $data, int $schoolId, array &$lookups) => static::createRow($data, $schoolId, $lookups),
        );
    }

    /**
     * Highest numeric suffix of PR-<year>-<seq> currently used by this school.
     */
    protected static function currentRequestSequence(int $schoolId): int
    {
        $prefix = 'PR-'.now()->year.'-';

        $max = ProcurementRequest::withoutTenantScope()
            ->where('school_id', $schoolId)
            ->where('request_number', 'like', $prefix.'%')
            ->get('request_number')
            ->pluck('request_number')
            ->map(fn (string $number): int => (int) substr($number, strlen($prefix)))
            ->max() ?: 0;

        return (int) $max;
    }

    /**
     * Read the mapped column of the uploaded file and return only the values
     * that do not yet exist in the reference model, sorted for stable indices.
     */
    protected static function unknownReferenceValues(string $filePath, int $schoolId, array $columnMap, string $fieldKey): array
    {
        $candidates = static::readReferenceValues($filePath, $columnMap, $fieldKey);
        $reference = static::referenceFields()[$fieldKey] ?? null;

        if ($reference === null || empty($candidates)) {
            return [];
        }

        $existing = $reference['model']::withoutTenantScope()
            ->where('school_id', $schoolId)
            ->pluck($reference['column'])
            ->map(fn ($value): string => strtolower(trim((string) $value)))
            ->flip();

        $unknown = [];
        foreach ($candidates as $value) {
            if (! $existing->has(strtolower($value))) {
                $unknown[] = $value;
            }
        }

        return array_values($unknown);
    }

    protected static function validateAndNormalize(array &$data, array $lookups): array
    {
        $errors = [];

        $itemNames = static::splitValues((string) ($data['item_names'] ?? ''));

        if ($itemNames === []) {
            $errors[] = static::columns()['item_names']['label'].' is required (column empty or not mapped).';
        }

        $quantities = static::splitValues((string) ($data['item_quantities'] ?? ''));
        $costs = static::splitValues((string) ($data['estimated_unit_cost'] ?? ''));

        $data['items'] = [];

        foreach ($itemNames as $i => $name) {
            $quantity = (int) ($quantities[$i] ?? ($quantities[0] ?? '1'));
            $quantity = max(1, $quantity);

            $cost = $costs[$i] ?? ($costs[0] ?? '0');
            $cost = is_numeric($cost) ? (float) $cost : 0.0;

            $data['items'][] = [
                'item_name' => $name,
                'quantity' => $quantity,
                'estimated_unit_cost' => $cost,
            ];
        }

        if ($quantities !== []) {
            foreach ($quantities as $qty) {
                if (! is_numeric($qty) || (int) $qty < 1) {
                    $errors[] = 'Item quantities must be whole numbers of at least 1.';
                    break;
                }
            }
        }

        if ($costs !== []) {
            foreach ($costs as $cost) {
                if (! is_numeric($cost)) {
                    $errors[] = 'Estimated unit costs must be numbers.';
                    break;
                }
            }
        }

        $data['status'] = strtolower(trim($data['status'] ?? ''));
        if ($data['status'] !== '' && ! in_array($data['status'], ['draft', 'pending_approval', 'approved', 'rejected'], true)) {
            $errors[] = 'Status must be one of: draft, pending_approval, approved, rejected.';
        }

        $data['urgency'] = strtolower(trim($data['urgency'] ?? ''));
        if ($data['urgency'] !== '' && ! in_array($data['urgency'], ['low', 'medium', 'high', 'emergency'], true)) {
            $errors[] = 'Urgency must be one of: low, medium, high, emergency.';
        }

        $department = trim($data['department'] ?? '');

        if ($department !== '') {
            $departmentId = $lookups['departmentIndex'][strtolower($department)] ?? null;

            if ($departmentId !== null) {
                $data['_department_id'] = $departmentId;
                $data['_create_department'] = false;
            } else {
                $policy = static::referencePolicy($lookups, 'department', $department);

                if ($policy === 'skip') {
                    $data['_department_id'] = null;
                    $data['_create_department'] = false;
                } else {
                    // Default (and the "create" option) provisions the record.
                    $data['_department_id'] = null;
                    $data['_create_department'] = true;
                }
            }
        } else {
            $data['_department_id'] = null;
            $data['_create_department'] = false;
        }

        return $errors;
    }

    protected static function referencePolicy(array $lookups, string $fieldKey, string $value): string
    {
        $missingRefs = $lookups['missingRefs'] ?? [];

        foreach (array_keys($missingRefs[$fieldKey] ?? []) as $index) {
            $unknownValues = $lookups['unknownDepartments'] ?? [];

            if (($unknownValues[(int) $index] ?? null) === $value) {
                return (string) ($missingRefs[$fieldKey][$index] ?? 'create');
            }
        }

        return 'create';
    }

    protected static function createRow(array $data, int $schoolId, array &$lookups): void
    {
        $departmentId = $data['_department_id'];

        if (($data['_create_department'] ?? false) && $departmentId === null) {
            $departmentId = static::createDepartment($data['department'], $schoolId, $lookups);
        }

        $lookups['seq']++;

        $request = ProcurementRequest::create([
            'school_id' => $schoolId,
            'request_number' => 'PR-'.now()->year.'-'.str_pad((string) $lookups['seq'], 5, '0', STR_PAD_LEFT),
            'requester_id' => $lookups['requesterId'],
            'department_id' => $departmentId,
            'status' => $data['status'] !== '' ? $data['status'] : 'draft',
            'urgency' => $data['urgency'] !== '' ? $data['urgency'] : 'medium',
            'purpose' => trim($data['purpose'] ?? '') !== '' ? $data['purpose'] : null,
            'notes' => trim($data['notes'] ?? '') !== '' ? $data['notes'] : null,
        ]);

        foreach ($data['items'] as $item) {
            ProcurementRequestItem::create([
                'procurement_request_id' => $request->id,
                'item_name' => $item['item_name'],
                'quantity' => $item['quantity'],
                'estimated_unit_cost' => $item['estimated_unit_cost'],
            ]);
        }
    }

    protected static function createDepartment(string $name, int $schoolId, array &$lookups): int
    {
        $name = trim($name);

        if (isset($lookups['departmentIndex'][strtolower($name)])) {
            return $lookups['departmentIndex'][strtolower($name)];
        }

        $baseCode = strtoupper(Str::slug($name, '-'));
        $code = $baseCode ?: 'DEPT';
        $suffix = 1;

        while (isset($lookups['existingCodes'][$code])) {
            $suffix++;
            $code = $baseCode.'-'.$suffix;
        }

        $department = Department::withoutTenantScope()->create([
            'school_id' => $schoolId,
            'name' => $name,
            'code' => $code,
            'type' => 'administrative',
            'status' => 'active',
        ]);

        $lookups['departmentIndex'][strtolower($name)] = $department->id;
        $lookups['existingCodes'][$code] = true;

        return $department->id;
    }
}